service: pricemap-scanner

frameworkVersion: ">=3"

plugins:
  - serverless-s3-sync
  
provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  stage: ${opt:stage, 'serverless'}
  profile: ${self:custom.profiles.${self:provider.stage}}
  environment:
    BUCKET_NAME: ${self:service}-${self:provider.stage}

custom:
  profiles:
    local: default
    serverless: serverless

  s3Sync:
    - bucketName: ${self:provider.environment.BUCKET_NAME}
      localDir: build

resources:
  Resources:
    #===========================================================================
    StaticSite:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.BUCKET_NAME}
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
    #===========================================================================
    StaticSiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticSite
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
                - s3:GetObject
              Resource:
                Fn::Join: [
                  "", [
                    "arn:aws:s3:::",
                    {
                      "Ref": "StaticSite"
                    },
                    "/*"
                  ]
                ]
    #===========================================================================